#!/env/bin bash


DEB_PACKAGE_TEMPLATE_DIRECTORY="package/DEBIAN"

PACKAGE=$(grep -hr "Package" $DEB_PACKAGE_TEMPLATE_DIRECTORY/control | awk '{print $2}')
VERSION=$(grep -hr "Version" $DEB_PACKAGE_TEMPLATE_DIRECTORY/control | awk '{print $2}')
ARCHITECTURE=$(grep -hr "Architecture" $DEB_PACKAGE_TEMPLATE_DIRECTORY/control | awk '{print $2}')
INSTALLATION_DIRECTORY_BASE="/usr/local/bin"
OUTPUT_DIRECTORY="package"
RELEASE_DIRECTORY="${OUTPUT_DIRECTORY}/${PACKAGE}_${VERSION}_${ARCHITECTURE}"
INSTALLATION_DIRECTORY_BASE="/usr/local/bin"
INSTALLATION_DIRECTORY="${RELEASE_DIRECTORY}${INSTALLATION_DIRECTORY_BASE}"


mkdir $RELEASE_DIRECTORY
cp -r $DEB_PACKAGE_TEMPLATE_DIRECTORY $RELEASE_DIRECTORY

#mkdir -p $INSTALLATION_DIRECTORY
echo $INSTALLATION_DIRECTORY
DESTDIR=$RELEASE_DIRECTORY make -j4 install

dpkg-deb --build $RELEASE_DIRECTORY
