#!/env/bin bash


DEB_PACKAGE_TEMPLATE_DIRECTORY="package/DEBIAN"

GIT_BRANCH=$(git branch | awk '{print $2}')

PACKAGE=$(grep -hr "Package" $DEB_PACKAGE_TEMPLATE_DIRECTORY/control | awk '{print $2}')
VERSION=$(grep -hr "Version" $DEB_PACKAGE_TEMPLATE_DIRECTORY/control | awk '{print $2}')-$GIT_BRANCH
ARCHITECTURE=$(grep -hr "Architecture" $DEB_PACKAGE_TEMPLATE_DIRECTORY/control | awk '{print $2}')
INSTALLATION_DIRECTORY_BASE="/usr/local/bin"
OUTPUT_DIRECTORY="package"
RELEASE_DIRECTORY="${OUTPUT_DIRECTORY}/${PACKAGE}_${VERSION}_${ARCHITECTURE}"
INSTALLATION_DIRECTORY_BASE="/usr/local/bin"
INSTALLATION_DIRECTORY="${RELEASE_DIRECTORY}${INSTALLATION_DIRECTORY_BASE}"


mkdir $RELEASE_DIRECTORY
cp -r $DEB_PACKAGE_TEMPLATE_DIRECTORY $RELEASE_DIRECTORY

#mkdir -p $INSTALLATION_DIRECTORY
echo $INSTALLATION_DIRECTORY
DESTDIR=$RELEASE_DIRECTORY make -j4 install



SHA256SUM=$(find $RELEASE_DIRECTORY -type f | grep -v DEBIAN) | sed 's,\./,/,g'

echo "Sha256 File Checksums:"
echo "${SHA256SUM}"


dpkg-deb --build $RELEASE_DIRECTORY
